export interface DubaiExcursion {
  id: string;
  nameUz: string;
  nameRu: string;
  descUz: string;
  descRu: string;
  image: string;
  type: "free" | "paid";
  rating?: number;
  reviewCount?: string;
  priceUsd?: number;
  priceNote?: string;
  durationUz: string;
  durationRu: string;
  rankPosition?: number;
  bestFor?: string[];
  included?: string[];
  highlight?: string;
  tipsUz?: string;
  tipsRu?: string;
}

export interface ExcursionFAQ {
  qUz: string;
  qRu: string;
  aUz: string;
  aRu: string;
}

export const DUBAI_FREE_EXCURSIONS: DubaiExcursion[] = [
  {
    id: "jumeirah-beach",
    nameUz: "Jumeirah Public Beach",
    nameRu: "Пляж Джумейра",
    descUz: "Dubai ning eng mashhur va toza plyaji. Kristall ravshan suv, oq qum, va qulay muhit barcha foydalanuvchilar uchun. Jumeirah Beach — butun dunyo turistlari uchun taqqoslanuvchi joy. Bepul kiresh, yaxshi tavsif, va to'liq xizmatlar (kabinalar, reseptsiya, kafeler).",
    descRu: "Самый известный и чистый пляж Дубая. Кристально чистая вода, белый песок и прекрасная атмосфера. Jumeirah Beach — это место мечты для пляжного отдыха. Полностью бесплатный вход, отличные условия и полный спектр услуг (кабинки для переодевания, спасатели, кафе).",
    image: "https://cdn.pixabay.com/photo/2016/08/01/20/25/dubai-1562315_960_720.jpg",
    type: "free",
    rating: 4.7,
    reviewCount: "8,500+",
    durationUz: "Yarım kun yoki butun kun",
    durationRu: "Полдня или целый день",
    bestFor: ["Oila", "Juftlik", "Yosh turizm"],
    highlight: "Dunyodagi eng mashhur plyaj",
    tipsUz: "Erkaklar va ayollar uchun alohida xonalar. Qorning 9:00-18:00 gacha ochiq. Kechki 16:00 dan boshlab tenglashtirilgan quyosh va kop odam.",
    tipsRu: "Раздельные кабинки для переодевания. Открыт с 9:00 до 18:00. После 16:00 меньше людей и золотой закат.",
  },
  {
    id: "dubai-fountain",
    nameUz: "Dubai Fountain & Dubai Mall",
    nameRu: "Поющий фонтан и Dubai Mall",
    descUz: "Dunyoning eng katta va eng qiziqarli fontan shou. Har 30-40 minutda klassik muzika, opera, va zamonaviy songlar bilan fantastik shou. Dubai Mall ning markazida joylashgan — bepul tomosha, registratsiya yo'q. Kechki shou eng chiroyli, maqtovchi sharh olib keldi.",
    descRu: "Самый большой фонтан в мире с потрясающим световым и музыкальным шоу. Показы каждые 30-40 минут под классическую музыку, оперу и современные песни. Находится в центре Dubai Mall — полностью бесплатно, никакой регистрации. Вечерние шоу (19:00, 20:30, 22:00) особенно красивы!",
    image: "https://cdn.pixabay.com/photo/2017/02/02/18/42/dubai-fountain-2031991_960_720.jpg",
    type: "free",
    rating: 4.8,
    reviewCount: "12,000+",
    durationUz: "1-2 soat",
    durationRu: "1-2 часа",
    bestFor: ["Oila", "Yosh turizm", "Fotofanlar"],
    highlight: "#1 bepul attractions",
    tipsUz: "Kechki shou (19:00, 20:30, 22:00) eng zo'r. Dubai Mall ning 2-qavat terrasasidan ko'rish juda yaxshi.",
    tipsRu: "Вечерние шоу самые красивые. Смотрите с верхней террасы Dubai Mall для лучшего вида. Приходите за 15 минут до начала.",
  },
  {
    id: "gold-souk",
    nameUz: "Gold Souk & Spice Souk (Dubai Creek)",
    nameRu: "Золотой рынок и Базар специй",
    descUz: "Dubai ning tarixiy markazi — 350+ oltinchi do'kon va aromatic baharat bazari. Dunyo mashhur — eng yaxshi narxlar va katta bargaining (50% chegirmani olish mumkin!). Eski Dubai madaniyati, rangli atmosfera, va yaxshi tavsif. Piyoda yurish, foto-surat, va tarix bir joyda.",
    descRu: "Историческое сердце Дубая с 350+ ювелирными магазинами и ароматным базаром специй. Мировой рынок золота с лучшими ценами и огромным потенциалом торга (50% скидка реальна!). Аутентичная атмосфера, яркие цвета, и богатая история. Идеально для покупок, фотографий и культурного погружения.",
    image: "https://cdn.pixabay.com/photo/2017/01/25/22/00/gold-2008374_960_720.jpg",
    type: "free",
    rating: 4.5,
    reviewCount: "9,200+",
    durationUz: "2-4 soat",
    durationRu: "2-4 часа",
    bestFor: ["Xaridchilar", "Madaniyat sevgilar", "Fotofanlar"],
    highlight: "Dunyo mashhur oltinchi bazari — 50% chegirma!",
    tipsUz: "Bargain qilish majburiy — 40-50% chegirmani tlab oling. Erta sabah (8:00-10:00) yoki kechki (17:00+) vaqtda kam odam. Toza pul bilan kelgandan yaxshi (tanga chiqadi).",
    tipsRu: "Торг обязателен — просите скидку 40-50%. Приходите рано утром (8:00-10:00) или поздно вечером. Возьмите наличные деньги (мелочь помогает).",
  },
  {
    id: "dubai-marina",
    nameUz: "Dubai Marina & JBR Beach Walk",
    nameRu: "Дубайская Марина и прогулка по пляжу",
    descUz: "Zamonaviy dengiz bo'yi promenadida piyoda yurish. Qovarish kemalar, yoqtirish restoranlar, kafeler, va butun shuningdek shahar ko'rinishi. Kechki promenad (19:00-21:00) juda romantik va suvsiz, ko'pik tolasiga to'lq. JBR Beach — yosh turizm va sport sevgilar uchun mashhur.",
    descRu: "Красивая прогулка по современной набережной с парусниками и яхтами. Множество ресторанов, кафе и магазинов с видом на город. Вечерняя прогулка (19:00-21:00) особенно романтична и безлюдна. JBR Beach — популярно среди молодежи и любителей спорта.",
    image: "https://cdn.pixabay.com/photo/2016/11/12/21/50/marina-1819394_960_720.jpg",
    type: "free",
    rating: 4.6,
    reviewCount: "7,800+",
    durationUz: "1-2 soat",
    durationRu: "1-2 часа",
    bestFor: ["Juftlik", "Yosh turizm", "Fotofanlar"],
    highlight: "Kechki romantik promenad",
    tipsUz: "Kechki 19:00-21:00 eng yaxshi vaqti. Qoniqli restoran topish uchun oldindan joyni ko'rib qo'ying. Suvsiz, sho'x qoyilgan va boshqa tomoni tinchliq.",
    tipsRu: "Вечер (19:00-21:00) — лучшее время. Забронируйте ресторан заранее. Очень красивые виды на закат.",
  },
  {
    id: "al-fahidi",
    nameUz: "Al Fahidi Historic District",
    nameRu: "Исторический район Аль-Фахиди",
    descUz: "Dubai ning eng qadimiy qismi — windtowers, o'zbekcha arxitektura, va tarixiy museylar. Piyoda yurish juda zavql — har bir burchakda fotosurat imkoniyatlari. Sheikh Mohammad's House, Dubai Museum, va boshqa tarixiy joy barlarni ko'rish mumkin. Qulay, so'qquvchi, va tinchliq muhit.",
    descRu: "Самая старая часть Дубая с традиционной архитектурой и историческими музеями. Прекрасное место для пешеходных прогулок — каждый угол идеален для фотографий. Музей Шейха Мохаммеда, Дубайский музей и другие достопримечательности. Спокойная, тихая и культурная атмосфера.",
    image: "https://cdn.pixabay.com/photo/2016/03/21/14/00/dubai-1271529_960_720.jpg",
    type: "free",
    rating: 4.5,
    reviewCount: "6,500+",
    durationUz: "2-3 soat",
    durationRu: "2-3 часа",
    bestFor: ["Madaniyat sevgilar", "Fotofanlar", "Oila"],
    highlight: "Dubai ning qadimiy tarix",
    tipsUz: "Sabah ertalab 8:00-10:00 kilganning yaxshi (kam issiqlik, kam odam). Dubai Museum (5 AED, ~$1.50) tashrif qilsangiz ancha yaxshi bo'ladi.",
    tipsRu: "Приходите рано утром (8:00-10:00) — меньше жары и людей. Посетите Дубайский музей (5 AED, ~$1.50) для полного впечатления.",
  },
];

export const DUBAI_PAID_EXCURSIONS: DubaiExcursion[] = [
  {
    id: "desert-safari",
    nameUz: "Desert Safari — Cho'l Safarisi & BBQ Dinner",
    nameRu: "Пустынное сафари — Дюнный баш и ужин BBQ",
    descUz: "#1 ekskursiya Dubai da! 4WD mashinada dune bashing, tuya minish, sandboarding, asbob ranglarini mushoma, Bedouin xamligi, raqs shou (belly dancing, Tanoura), va lobya-qazi ziyofat. 6-7 soatlik unutolmas sayohat quyosh botgan vaqtida. Professional gidlar, xavfsizlik barcha, va 12,000+ sharh bilan 4.6/5 yulduz.",
    descRu: "#1 экскурсия в Дубае! 4WD дюнный баш, катание на верблюдах, сэндбординг, палатка Бедуинов, живая музыка, танцы живота и Танура, ужин BBQ с местными блюдами. 6-7 часов невероженного приключения на закате. Профессиональные гиды, полная безопасность, 4.6/5 звёзд (12,000+ отзывов).",
    image: "https://cdn.pixabay.com/photo/2019/12/15/11/09/desert-4698508_960_720.jpg",
    type: "paid",
    rating: 4.6,
    reviewCount: "12,000+",
    priceUsd: 50,
    priceNote: "kishi boshiga / с человека",
    durationUz: "6-7 soat (16:00 dan 23:00 gacha)",
    durationRu: "6-7 часов (с 16:00 до 23:00)",
    rankPosition: 1,
    bestFor: ["Oila", "Sarguzasht sevgilar", "Fotofanlar"],
    included: ["4WD transport", "Tuya minish", "BBQ ziyofat", "Raqs shou", "Rasmlar"],
    highlight: "Dunyoning #1 desert experience!",
    tipsUz: "May-Sentabrda narxi $30-35 (issiqlik), Oktabrdan Aprelgacha $50-70. Kichik bolalari va oilalar uchun best. Telefon va kamera kerak — sunset va raqslar juda chiroyli!",
    tipsRu: "май-сентябрь дешевле ($30-35 за жару), октябрь-апрель дороже ($50-70). Лучше для семей и малышей. Возьмите камеру — закат и танцы невероятны!",
  },
  {
    id: "burj-khalifa",
    nameUz: "Burj Khalifa At The Top (124-qavat)",
    nameRu: "Бурдж-Халифа — 124-й этаж",
    descUz: "Dunyoning eng baland binosi (828m) — asasosi 2716 feet balandlikda. Potentsial 360-daraja shahar, dengiz, va cho'l ko'rinishi. VR bo'sh joylar, high-tech binokulyar, green screen fotosurat. Quyosh botish vaqtida (17:30-18:30) eng zo'r. 4.6/5 yulduz, 9,000+ sharh. Non-prime (kundag) $(47-58), Prime (quyosh) $(75-100).",
    descRu: "Самое высокое здание в мире (828 м) — виды с 2716 футов высоты. 360-градусный вид на город, море и пустыню. VR опыт, высокотехнологичный телескоп, фото на зелёном экране. Закат (17:30-18:30) — лучшее время. 4.6/5 звёзд (9,000+ отзывов). Дневной ($47-58) vs закат ($75-100).",
    image: "https://cdn.pixabay.com/photo/2017/01/26/19/38/burj-khalifa-2012688_960_720.jpg",
    type: "paid",
    rating: 4.6,
    reviewCount: "9,000+",
    priceUsd: 45,
    priceNote: "kishi boshiga / с человека",
    durationUz: "1.5-2 soat",
    durationRu: "1.5-2 часа",
    rankPosition: 2,
    bestFor: ["Juftlik", "Oila", "Fotofanlar"],
    included: ["Bilkent", "VR", "Fotosurat", "High-tech teleskop"],
    highlight: "Dunyoning #1 binosi — 828m balandligi!",
    tipsUz: "Biletni onlayndan avvaldan qilsangiz 20% arzonroq. Quyosh botish vaqti (Prime) eng mashhur — 1-2 hafta oldindan buyurtma qiling. Ombor shartida (5-10°C soguq).",
    tipsRu: "Билеты онлайн заранее на 20% дешевле. Закат (Prime time) самый популярный — забронируйте за 1-2 недели. На верхнем этаже ветренно и холодно.",
  },
  {
    id: "abu-dhabi",
    nameUz: "Abu Dhabi Full Day — Sheikh Zayed Grand Mosque",
    nameRu: "Абу-Даби — Мечеть Шейха Зайда (полный день)",
    descUz: "Dubaydan Abu Dabiga (2 soat masofada) kunburun sayohat. Dunyoning eng go'zal masjidlaridan biri — putir marmar, crystal chandelier, Swarovski-crystal qoplangan devorlar. 99,000 m² qo'pni ustiga 40,000 nufusli musolmon. Professional gidlar — juda ilmli va maslahatchilar. Etihad Towers, Qasr Al Watan saroyini ko'rish. 4.7/5 yulduz.",
    descRu: "Полный день из Дубая в Абу-Даби (2 часа в пути). Одна из самых красивых мечетей в мире — белый мрамор, хрустальные люстры, стены с кристаллами Сваровски. Площадь 99,000 м², вмещает 40,000 молящихся. Профессиональные гиды (очень знающие). Этихад Тауэрс и дворец Каср аль-Ватан. 4.7/5 звёзд.",
    image: "https://cdn.pixabay.com/photo/2018/01/16/21/28/mosque-3086285_960_720.jpg",
    type: "paid",
    rating: 4.7,
    reviewCount: "8,500+",
    priceUsd: 80,
    priceNote: "kishi boshiga / с человека",
    durationUz: "9-10 soat (butun kun)",
    durationRu: "9-10 часов (целый день)",
    rankPosition: 3,
    bestFor: ["Oila", "Madaniyat sevgilar", "Diniy turizm"],
    included: ["Masjid kirish", "Professional gid", "Transport", "Sug'urta"],
    highlight: "Dunyoning #1 go'zal masjidi!",
    tipsUz: "Ayollar uchun hijob va long qolfa kerak (masjidga kirishdan oldin beriladi). Erkaklar uchun long pants yaxshi emas — short pants ko'p. Gid professionali va ilmli — suallar bersa ajoyib javoblar beradi.",
    tipsRu: "Женщины должны носить платок и длинные одежды в мечети (выдаются на входе). Мужчины в длинных брюках (короткие штаны не рекомендуются). Гиды очень знающие и дружелюбные.",
  },
  {
    id: "dhow-cruise",
    nameUz: "Dhow Cruise — Kechki Ziyofat Dubai Creek da",
    nameRu: "Парусник Доу — Ужин на корабле по Крику",
    descUz: "Rang-barang mashinada (traditional Arab sailboat) Dubai Creek bo'ylab ikki-soatli sayohat. Sharqiy va xarb ovqatlar, BBQ, vegetarian variantlar. Tashliq va choy bepul. Tonzali musiqachi va ba'zan raqs shou. Kechki (19:00 va 21:00) vaqtda, quyosh botgan vaqtda eng zo'r. 4.5/5 yulduz, 7,000+ sharh. Juda romantik!",
    descRu: "На традиционной арабской парусной лодке по Дубайскому Крику. 2-3 часовой круиз с ужином, включая блюда разных кухонь, BBQ, вегетарианские опции. Напитки включены. Живая музыка и иногда танцы. Вечер (19:00, 21:00) особенно красив на закате. 4.5/5 звёзд (7,000+ отзывов). Очень романтично!",
    image: "https://cdn.pixabay.com/photo/2017/06/06/23/09/sailboat-2378313_960_720.jpg",
    type: "paid",
    rating: 4.5,
    reviewCount: "7,000+",
    priceUsd: 30,
    priceNote: "kishi boshiga / с человека",
    durationUz: "2-3 soat",
    durationRu: "2-3 часа",
    rankPosition: 4,
    bestFor: ["Juftlik", "Romantic sevgilar", "Oila"],
    included: ["Dinner buffet", "Ichimliklar", "Live music", "Creek views"],
    highlight: "Kechki romantik sailboat!",
    tipsUz: "Juftlik uchun juda romantik! Erkaklar formal pakalyni qoldirib casual bo'lishi juda yaxshi. Biletlarni oldindan buyurtma qiling (10-15% arzonroq).",
    tipsRu: "Идеально для молодоженов и романтичных пар! Мужчины могут оставить формальный пиджак. Забронируйте заранее (скидка 10-15%).",
  },
  {
    id: "xline-zipline",
    nameUz: "XLine Dubai Marina Zipline — 1 km Zipline at 80 km/h",
    nameRu: "XLine Дубай Марина — 1 км на зиплайне 80 км/ч",
    descUz: "Dunyoning eng uzun shahar zipline! 1 km uzunlik, 80 km/h speed, Marina shuuning ustiga parvoz. Superman pozitsiyasida uchar — asasosi qor bilan ko'rinish. Professional raskhodning sho'xlik adrenalin. 4.8/5 yulduz, 1,500+ sharh. Boshiga telegramma va video beriladi!",
    descRu: "Самый длинный городской зиплайн в мире! 1 км полёта на 80 км/ч над Дубайской Мариной. Позиция Супермена — невероятные ощущения и виды. Профессиональное оборудование, дружелюбный персонал. 4.8/5 звёзд (1,500+ отзывов). Профессиональные фото и видео включены!",
    image: "https://cdn.pixabay.com/photo/2017/12/15/13/51/zip-lining-3021988_960_720.jpg",
    type: "paid",
    rating: 4.8,
    reviewCount: "1,500+",
    priceUsd: 150,
    priceNote: "kishi boshiga / с человека",
    durationUz: "1.5 soat (registration + flying)",
    durationRu: "1.5 часа (регистрация + полёт)",
    rankPosition: 5,
    bestFor: ["Sarguzasht sevgilar", "Yosh turizm", "Fotofanlar"],
    included: ["Harness", "Safety equipment", "Professional photos", "Video"],
    highlight: "Dunyoning #1 urban zipline — 80 km/h!",
    tipsUz: "Erkaklar va ayollar barcha qila oladi (16+ yosh kerak). Qiyofa yaxshi bo'lsi — fotosurat juda zo'r! Sunrise vaqti (06:30) ko'p kam odam, eng yaxshi chiroyli vaqti.",
    tipsRu: "Все могут летать (16+ лет). Красивая одежда — фото будут отличные! Рассвет (06:30) — меньше людей и красивый свет.",
  },
  {
    id: "dune-buggy",
    nameUz: "Dune Buggy & Quad Bike — Self-Drive Desert",
    nameRu: "Багги и квадроцикл — Сафари по пустыне",
    descUz: "O'z qo'lingizda powerful dune buggy yoki quad bike uchmasizlik! Desert bo'ylab 30 minutdan 6 soatgacha sayohat. Professional guidelar, xavfsizlik sho'xlik, yaxshi-ta'mirlangan asboblar. Hammasi bepul training bilan. 4.8/5 yulduz, 2,000+ sharh. Adrenalin cherasi maksimal!",
    descRu: "Управляйте мощным багги или квадроциклом самостоятельно! От 30 минут до 6 часов по пустыне. Профессиональные гиды, безопасность, обслуженное оборудование. Включена полная подготовка. 4.8/5 звёзд (2,000+ отзывов). Максимум адреналина!",
    image: "https://cdn.pixabay.com/photo/2016/04/02/19/42/quad-1303535_960_720.jpg",
    type: "paid",
    rating: 4.8,
    reviewCount: "2,000+",
    priceUsd: 110,
    priceNote: "kishi boshiga / с человека",
    durationUz: "2-6 soat (variantlar bor)",
    durationRu: "2-6 часов (разные варианты)",
    rankPosition: 6,
    bestFor: ["Sarguzasht sevgilar", "Yosh turizm", "Erkak-ayollar"],
    included: ["Dune buggy/quad", "Helmet", "Safety gear", "Professional guide"],
    highlight: "Self-drive desert thrill!",
    tipsUz: "Erkakning license kerak. Qalinmi va asbobga jozibali — toza kiyimda tez-tezlik bilan buladi! Erkaklar uchun eng sevdilar qilishlar.",
    tipsRu: "Нужны водительские права. Одежда потеряется в песке — возьмите тонкую. Мужчины обожают это занятие!",
  },
  {
    id: "museum-future",
    nameUz: "Museum of the Future",
    nameRu: "Музей будущего",
    descUz: "Futuristik binolar (2071 yil setting) — interaktiv yo'rinishlar, hologram, artificial intelligence, va virtual reality. Tarix, adab-axloq, va zamonaviy shuning o'rni. Arkitektura juda go'zal — 'ring' shaklin. Guiding yo'q — o'zingiz kashf eting. 4.3/5 yulduz, 3,500+ sharh. Kunning boshida (9:00-11:00) kam odam.",
    descRu: "Интерактивные выставки о будущем (2071 год), голограммы, AI, виртуальная реальность. История, искусство и технология в одном месте. Архитектура здания уникальна — форма кольца. Без гида — исследуйте сами. 4.3/5 звёзд (3,500+ отзывов). Лучше утром (9:00-11:00).",
    image: "https://cdn.pixabay.com/photo/2017/03/02/08/44/futuristic-2110302_960_720.jpg",
    type: "paid",
    rating: 4.3,
    reviewCount: "3,500+",
    priceUsd: 50,
    priceNote: "kishi boshiga / с человека",
    durationUz: "2-3 soat",
    durationRu: "2-3 часа",
    rankPosition: 7,
    bestFor: ["Texnologiya sevgilar", "Oila", "Yosh turizm"],
    included: ["Kiresh", "Interaktiv yo'rinishlar", "VR experience"],
    highlight: "Futuristik museum — 2071 yilga safar!",
    tipsUz: "Kunning boshida (9:00-11:00) kam odam va qulay. VR ko'zgusi — sharh olishing oldin sinab qo'ying. Baribir, unumli yaxshi — bilet narxiga arziydi.",
    tipsRu: "Приходите утром (9:00-11:00) — меньше толпы. VR очки — попробуйте перед покупкой. Хотя рейтинг 4.3, опыт того стоит.",
  },
  {
    id: "platinum-safari",
    nameUz: "Platinum Desert Safari — Luxury Arabian Oryx Spotting",
    nameRu: "Платинум сафари — Люкс опыт с газелями",
    descUz: "Desert Safari'ning luxury upgrading! Dubai Desert Conservation Preserve'da private Range Rover. Native Arabian Oryx (voh) spotting — unique wildife experience. Sunset canapé, falconry demonstration, royal retreat lake sanctuary. Gourmet dinner. 4.8/5 yulduz, 800+ sharh. VIP taassumlari!",
    descRu: "Люкс версия пустынного сафари! В приватном Range Rover по Dubai Desert Conservation Reserve. Слежение за арабскими газелями — уникальное дикое животное. Закусочки на закате, демонстрация соколиной охоты, королевский рай озера. Изысканный ужин. 4.8/5 звёзд. Премиум впечатление!",
    image: "https://cdn.pixabay.com/photo/2019/12/15/11/09/desert-4698508_960_720.jpg",
    type: "paid",
    rating: 4.8,
    reviewCount: "800+",
    priceUsd: 130,
    priceNote: "kishi boshiga / с человека",
    durationUz: "7-8 soat",
    durationRu: "7-8 часов",
    rankPosition: 8,
    bestFor: ["Luxury sevgilar", "Juftlik", "VIP turizm"],
    included: ["Private Range Rover", "Oryx spotting", "Falconry show", "Gourmet dinner"],
    highlight: "Luxury desert experience!",
    tipsUz: "Juda Qimatli lekin yaxshi ko'rinish — VIP ta'alluq. Erkaklar formal kiyim kiysin (quyosh botganda qulay). Eng mashhur — juftliklar va honey-moon qilinayotganlar.",
    tipsRu: "Дорого но стоит каждого доллара — люкс опыт. Мужчины могут быть в формальной одежде. Популярно у молодоженов!",
  },
];

export const DUBAI_EXCURSION_FAQS: ExcursionFAQ[] = [
  {
    qUz: "Dubayda qanday tekinga joylarga borsa bo'ladi?",
    qRu: "Какие бесплатные достопримечательности в Дубае?",
    aUz: "5 ta bepul ekskursiya: Jumeirah Beach (eng mashhur), Dubai Fountain (her kecha shou), Gold Souk (bargaining, 50% chegirma), Dubai Marina Walk (romantic), Al Fahidi Historic (tarix va fotosurat). Hamasi bepul, hammasi ichki qilinuvchi!",
    aRu: "5 бесплатных экскурсий: Пляж Джумейра (самый известный), Фонтан (каждый вечер шоу), Золотой рынок (торг 50%), Марина (прогулка), Аль-Фахиди (история). Все бесплатные, все интересные!",
  },
  {
    qUz: "Desert Safari qancha turadi va nima kiradi?",
    qRu: "Сколько стоит пустынное сафари и что включено?",
    aUz: "$50 kishi boshiga. Kiradi: 4WD dune bashing, tuya minish, BBQ ziyofat, Bedouin camp, raqs shou, transfer. 6-7 soatlik uzbek! May-Sentabrda $30-35 (issiq lekin qulay).",
    aRu: "$50 с человека. Включено: 4WD дюны, верблюды, ужин BBQ, палатка, танцы, трансфер. 6-7 часов приключений! Май-сентябрь дешевле ($30-35).",
  },
  {
    qUz: "XLine Zipline nima va qanday xavfsiz?",
    qRu: "Что такое XLine Zipline и безопасно ли это?",
    aUz: "Dunyoning eng uzun urban zipline — 1 km, 80 km/h speed, Marina ustida parvoz. Superman position'da uchar — juda qo'rquvli va zo'r! 4.8/5 yulduz, 1500+ sharh. Hech xavf yo'q — professional, xavfsizlik maxfiy.",
    aRu: "Самый длинный городской зиплайн в мире — 1 км на 80 км/ч над Мариной. Позиция Супермена — адреналин! 4.8/5 звёзд. Полностью безопасно — профессиональное оборудование.",
  },
  {
    qUz: "Burj Khalifaga bilet qancha va oldindan kerakmi?",
    qRu: "Сколько стоит билет в Бурдж-Халифу и заказывать ли заранее?",
    aUz: "$45-100 (vaqt va type'ga qarab). Quyosh botish (Prime) eng qimatli ($75-100) va mashhur — 2 hafta avvaldan buyurtma qiling. Kundag ($45-58) ham yaxshi. Onlayn bilet 20% arzonroq.",
    aRu: "$45-100 в зависимости от времени. Закат (Prime time) дороже ($75-100) и популярнее — забронируйте за 2 недели. Дневные билеты дешевле. Онлайн на 20% дешевле.",
  },
  {
    qUz: "Abu Dhabi sayohati qancha turadi va qanday?",
    qRu: "Сколько стоит тур в Абу-Даби и как туда добраться?",
    aUz: "$80 kishi boshiga, butun kun (9-10 soat). Dubaydan transport, Sheikh Zayed Mosque (go'zal!), Etihad Towers, Qasr Al Watan. Professional gid, sug'urta, ovqat. 4.7/5 yulduz. Madaniy va tarixiy juda yaxshi.",
    aRu: "$80 с человека, целый день (9-10 часов). Трансфер из Дубая, мечеть Шейха Зайда (красиво!), музеи. Профессиональный гид. 4.7/5 звёзд. Очень культурный опыт.",
  },
  {
    qUz: "Dune Buggy kimlarga va qanday qo'rquvli?",
    qRu: "Кто может ездить на багги и насколько это страшно?",
    aUz: "16+ yosh, driver's license kerak. Juda qo'rquvli emas — professional guide, safety gear, training. 4.8/5 yulduz, 2000+ sharh. Adrenalin lekin xavf yo'q. Erkaklar va ayollar barcha o'rnatavchi!",
    aRu: "16+ лет, водительские права. Не очень страшно — профессиональный гид, полная безопасность. 4.8/5 звёзд. Адреналин без риска. Все могут!",
  },
  {
    qUz: "Dhow Cruise kimlarga eng yaxshi — juftlik yoki oila?",
    qRu: "Для кого лучше Dhow Cruise — пара или семья?",
    aUz: "Ikkalasi ham yaxshi! Juftlik uchun eng romantik (kechki, sunset, muzika). Oila uchun ham — bolalar ovqat sevadi, senga qulay, safe, yaxshi musiqali. $30 kishi boshiga, 2-3 soat. Hech kim achitavchi yo'q!",
    aRu: "И то, и другое! Для пар очень романтично (вечер, закат, музыка). Для семей — дети любят еду, атмосфера спокойная, безопасно. $30 с человека. Все в восторге!",
  },
  {
    qUz: "Ekskursiyalar uchun jami qancha pul kerak — budget plani?",
    qRu: "Сколько денег нужно на все экскурсии — бюджет?",
    aUz: "Tekinga: $0 (5 ta). Top 3 pullik: Desert Safari $50 + Burj Khalifa $45 + Abu Dhabi $80 = $175. Agar XLine qo'ysangiz +$150 = $325 jami. Oilaga: tekinga + 2-3 pullik = $100-150 jami. Qulay narxlar!",
    aRu: "Бесплатные: $0 (5 экскурсий). Топ-3: Desert Safari $50 + Burj Khalifa $45 + Abu Dhabi $80 = $175. С XLine Zipline добавьте $150 = $325. Для семьи: бесплатные + 2-3 платные = $100-150 в сумме. Доступные цены!",
  },
];
